### ISSUE TITLE
FromPreview 样式细节问题

### ISSUE THREAD

**Issue by transtone** [airyland/vux#1021]
`@import '../../styles/weui/widget/weui_cell/weui_form/weui-form-preview.less';`
```less
.weui-form-preview__ft{
    position: relative;
    line-height: 50px;
    display: flex;
    &:after {
        .setTopLine(@weuiDialogLineColor);
    }
}
```
既然是setTopLine，就应该放到 before。

因为自己想加一个底线。现在必须加到 before里才生效，有点怪。
