### ISSUE TITLE
xheader  里面加个搜索框

### ISSUE THREAD

**Issue by zhonggedan** [airyland/vux#1028]
```html
<x-header :left-options="{showBack: false}" slot="header" style="width:100%;position:absolute;left:0;top:0;z-index:100; " default-back-link="/">
  <a slot="left" class="iconfontyyy ic">&#xe600;</a>
  <input type="text" />
  <a slot="right" class="iconfontyyy ic">&#xe617;</a>
</x-header>
```

``` css
.vux-header .vux-header-title, .vux-header h1 {
    margin: 0 88px;}
```
左右两边88px的边距， 用！important  都去不掉！
