### ISSUE TITLE
xicon使用起来不太方便,如果能像font-awesome那样就好了

### ISSUE THREAD

**Issue by RichardFans** [airyland/vux#1147]
其他组件都很棒,如果能提升xicon的效果就更好了.如通过class能够方便的设置颜色等

**Comment by lichunqiang** [comment]
基于SVG的，修改颜色的话可以参照demo。
每个生成个的icon都会设置有class属性：

```
<x-icon type="ios-ionic-outline" size="30"></x-icon>
```
->
```
class: vux-x-icon vux-x-icon-ios-ionic-outline
```
```css
.vux-x-icon {
  fill: #F70968;
}
```
