### ISSUE TITLE
tabbar-item中 icon 下边的字体颜色如何修改？

### ISSUE THREAD

**Issue by Wang-Kai** [airyland/vux#1338]
<img width="305" alt="2017-04-28 3 08 57" src="https://cloud.githubusercontent.com/assets/13144386/25518089/f0e881fc-2c24-11e7-9cd6-52fc5f78bcc3.png">

**Comment by cloook** [comment]
这个在哪里改的？

**Comment by Wang-Kai** [comment]
`.weui-bar__item_on{
    p.weui-tabbar__label{
        span{

            color: $main_blue !important;
        }
    }
}`

**Comment by Wang-Kai** [comment]
```css
.weui-bar__item_on{
    p.weui-tabbar__label{
        span{

            color: $main_blue !important;
        }
    }
}
```
