### ISSUE TITLE
有没有可能不依赖自带的这个 reset.css ？

### ISSUE THREAD

**Issue by terranc** [airyland/vux#1376]
现在项目里自带的 reset 里：
```css
* {
margin:0;
padding:0;
}
```

这极易影响到其它第三方插件的使用，而且当朋友文章页，就会导致得把内容里所有的元素复原成浏览器自带的，是个苦力活。
