### ISSUE TITLE
路由切换时fixed定位元素会产生一个位移的过程

### ISSUE THREAD

**Issue by keepfool** [airyland/vux#1822]
现象如下图：
![](http://i.imgur.com/itPMJab.gif)

fixed定位元素代码：
```css
.fixed {
  position: fixed;
  right: 50px;
  bottom: 100px;
  width: 50px;
  height: 50px;
  border-radius: 50%;
  background-color: #ff2fa0;
}
```
