### ISSUE TITLE
 swiper 怎么更具请求内容后设置高度?

### ISSUE THREAD

**Issue by ghost** [airyland/vux#2091]
tab和swiper做列表切换的时候 , swiper高度不能动态设置?

**Comment by airyland** [comment]
不能。swiper 不支持自适应高度，文档已经说明。

**Comment by roc2539** [comment]
那是否其他方案？

**Comment by wsq815** [comment]
现在是否有其它替代方案呢？

**Comment by xiaozhun** [comment]
用swiper当做列表用的时候，当高度设置超过屏幕后，元素不展示，不能向下拉伸。

**Comment by veluxa** [comment]
添加css , 覆盖默认高度：
```css
.vux-slider > .vux-swiper > .vux-swiper-item {
    height: calc(100% - 46px);
    overflow: auto;
}
```
