### ISSUE TITLE
Loding如何居中

### ISSUE THREAD

**Issue by iceuncle** [airyland/vux#2222]
希望提供Loading组件居中显示的方法

**Comment by airyland** [comment]
Loading 本来就是居中显示。

**Comment by airyland** [comment]
手动覆盖样式

``` css
.vux-loading .weui-toast {
  top: 50%;
  transform: translateX(-50%) translateY(-50%);
}
```
