### ISSUE TITLE
Feature - 有无计划对x-input组件增加focus才显示清除icon

### ISSUE THREAD

**Issue by natee** [airyland/vux#2567]
微信原生输入框对于清除icon的处理都是focus才显示，blur则隐藏

```javascript
    focusHandler ($event) {
      this.$el.classList.remove('vux-x-input-blur')
      this.$emit('on-focus', this.currentValue, $event)
    },
    onBlur ($event) {
      this.setTouched()
      this.validate()

      this.$el.classList.add('vux-x-input-blur')

      this.$emit('on-blur', this.currentValue, $event)
    },
```
```css
.vux-x-input-blur .weui-icon-clear{
  display: none;
}
```
