### ISSUE TITLE
FlexboxItem 宽度异常

### ISSUE THREAD

**Issue by emondora** [airyland/vux#2573]
Flexbox中有以下CSS代码，设置了宽度为0%，想请问下设置0%是基于什么考量？
```css
.vux-flexbox-item {
    flex: 1;
    -webkit-flex: 1;
    min-width: 20px;
    width: 0%;
}
```
问题描述：
代码压缩打包后，**width: 0%;** 变为了 **width:0;**，导致在 Cell 中使用 flexbox-item 出现宽度异常。
请问是否可直接移除 **width: 0%;** 这部分代码？

HTML代码结构：
```html
<cell>
  <div slot="title">支付方式</div>
  <flexbox>
    <span>图标</span>
    <flexbox-item>
      <p>演示文字</p>
      <small>工商银行</small>
      <small>（尾号 3333 | 快捷）</small>
    </flexbox-item>
  <flexbox>
</cell>
```

**以下为width:0%的截图，宽度正常**
![normal](https://user-images.githubusercontent.com/2391113/38074761-6e647646-3362-11e8-8264-881a4f216e6a.jpg)

**以下为width:0的截图，宽度异常**
![error](https://user-images.githubusercontent.com/2391113/38075266-642965c2-3364-11e8-8bde-0192206ff461.jpg)
