### ISSUE TITLE
vux-1px 如何自定义颜色

### ISSUE THREAD

**Issue by apkcore** [airyland/vux#2757]

**Comment by fanyongfeng** [comment]
覆盖他本身的 color   想 用 啥 颜色  就用啥 颜色

**Comment by apkcore** [comment]
咋覆盖呀大神，我只会直接抽出1px重写了~~~

**Comment by fanyongfeng** [comment]
覆盖他的样式呗

**Comment by unclay** [comment]
怎么覆盖样式与vux无关，可自行研究。
下面提供个自定义方式，可覆盖或者重新创建新类名来定义自己的1px样式
```less
/* App.vue */
@import '~vux/src/styles/1px.less';

.setNewLine(@c: #C7C7C7) {
  border: 1px solid @c;
  color: @c;
}
.setNewTopLine(@c: #C7C7C7) {
  border-top: 1px solid @c;
  color: @c;
}
.setNewBottomLine(@c: #C7C7C7) {
  border-bottom: 1px solid @c;
  color: @c;
}
.setNewLeftLine(@c: #C7C7C7) {
  border-left: 1px solid @c;
  color: @c;
}
.setNewRightLine(@c: #C7C7C7) {
  border-right: 1px solid @c;
  color: @c;
}
.newVux1px(@cn, @c: #C7C7C7) {
  .@{cn} { &:extend(.vux-1px); }
  .@{cn}-t { &:extend(.vux-1px-t); }
  .@{cn}-b { &:extend(.vux-1px-b); }
  .@{cn}-tb { &:extend(.vux-1px-tb); }
  .@{cn}-l { &:extend(.vux-1px-l); }
  .@{cn}-r { &:extend(.vux-1px-r); }

  .@{cn} {
    &:before {
      &:extend(.vux-1px:before);
      .setNewLine(@c);
    }
  }

  .@{cn}-t {
    &:before {
      &:extend(.vux-1px-t:before);
      .setNewTopLine(@c);
    }
  }

  .@{cn}-b {
    &:after {
      &:extend(.vux-1px-b:after);
      .setNewBottomLine(@c);
    }
  }

  .@{cn}-tb {
    &:before {
      &:extend(.vux-1px-tb:before);
      .setNewTopLine(@c);
    }
    &:after {
      &:extend(.vux-1px-tb:after);
      .setNewBottomLine(@c);
    }
  }

  .@{cn}-l {
    &:before {
      &:extend(.vux-1px-l:before);
      .setNewLeftLine(@c);
    }
  }

  .@{cn}-r {
    &:after {
      &:extend(.vux-1px-r:after);
      .setNewRightLine(@c);
    }
  }
}
.newVux1px(vux2-1px, red);
```
出现红色1px
```html
<div class="vux2-1px"></div>
<div class="vux2-1px-t"></div>
<div class="vux2-1px-b"></div>
<div class="vux2-1px-tb"></div>
<div class="vux2-1px-l"></div>
<div class="vux2-1px-r"></div>
```
