### ISSUE TITLE
[Bug Report] Confirm组件弹出时无法正常居中

### ISSUE THREAD

**Issue by LeoFengFromChina** [airyland/vux#2798]
### VUX version
2.9.1

### OS/Browsers version
windows7-Chrome（66.0.3359.170），Android

### Vue version
2.5.16

### Code

```html
    <div v-transfer-dom>
      <confirm v-model="showConfirm"
        title="警告" @on-confirm="onConfirm">
        <p>{{comfirmText}}</p>
      </confirm>
    </div>

--------------------------或者--------------------------------------

 <confirm v-model="showConfirm"
        title="警告" @on-confirm="onConfirm">
        <p>{{comfirmText}}</p>
 </confirm>

```

### Steps to reproduce
1、任何页面放置一个confirm；
2、让其弹出。弹出框位置出现动画：先是居中显示，大概0.3秒后，位置变动到偏左上角。使得整个comfirm框弹出后无法正常居中显示。

### What is Expected?
期待开发团队能尽快修复，使得弹出的Confirm框始终保持居中显示。

### What is actually happening?
目前，Confirm框弹出后无法正常居中显示。

**Comment by unclay** [comment]
demo是正常的，可以提供个repo看看？

**Comment by floait** [comment]
@unclay http://www.shiyicunxiao.com/wp-content/uploads/2018/05/TIM图片20180525170307.png

我也遇到了同样的问题,我的代码是这样的: 
首先我在main.js局部引入了组件:
```javascript
  import {Confirm, XHeader, Group, Cell, XButton,XInput, XTable , Toast,TransferDomDirective as TransferDom} from 'vux'

...
components: {
      Confirm,XButton, XInput, XHeader, Group, Cell, XTable
    }
...
```
我在调用的时候,confrim不居中
templete中是这样写的:
```html
    <div v-transfer-dom>
      <Confirm
        v-model="show"
        :close-on-confirm="false"
        :title="'aaa'"
        @on-confirm="onConfirm">
        <p style="text-align:center;">bbb</p>
      </Confirm>
    </div>
```

**Comment by floait** [comment]
解决了,不过感觉还是会有问题,我的项目里面就这一个弹窗,所以无所所谓了
找到这一段: 
```CSS
.weui-dialog {
    position: fixed;
    z-index: 5000;
    width: 80%;
    max-width: 300px;
    top: 50%;
    left: 50%;
    -webkit-transform: translate(-50%,-50%);
    transform: translate(-50%,-50%);
    background-color: #fff;
    text-align: center;
    border-radius: 3px;
    overflow: hidden;
}
```
其中的 
```CSS
 -webkit-transform: translate(-50%,-50%);
    transform: translate(-50%,-50%);
```
,使得dialog向左向上偏移了50%,导致最后不居中的,与官方文档对比,官方示例demo应该是全局引用的,使得dialog最终有三套不同的样式,不过那个transform怎么来的,还不太清楚,我自定义个dialog样式,
```CSS
 -webkit-transform: translate(0,0);
    transform: translate(0,0);
```
完美解决
