### ISSUE TITLE
search 提示文本垂直居中

### ISSUE THREAD

**Issue by transtone** [airyland/vux#314]
默认文本偏上，建议加上flex使其垂直居中：

``` css
.weui_search_text {
    display: flex;
    align-items: center;
    justify-content: center;
}
.weui_search_inner .weui_icon_search {
    top: inherit;
}
.weui_search_inner .weui_search_input, 
.weui_search_inner .weui_search_input::input-placeholder {
    display: inline-block;
    vertical-align: middle;
}
```
