### ISSUE TITLE
[Bug Report] 【菜逼的日子到头了】人工智能命名检测

### ISSUE THREAD

**Issue by LaoCheng-cjs** [airyland/vux#3593]
### VUX version
2.9.4

### OS/Browsers version
mac

### Vue version
2.6.10

### Code

```js
// console.log(require('vux/src/styles/reset.less'))
// const reset = require('vux/src/styles/reset.less');
const path = require('path')
// const CleanCSSPlugin = require('less-plugin-clean-css');
module.exports = {
  
  configureWebpack: config => {
      require('@vux/loader').merge(config, {
          options: {
            strictMath: true,
            noIeCompat: true,
          },
          plugins: [{name:'vux-ui'},{name:'less-theme', path: path.resolve(__dirname, "./src/assets/css/public.less")},{name: 'duplicate-style'}]
          // 
      })
  },
```

### Steps to reproduce

``` text
[vux-loader] 疑似不合法命名，将被忽略：.btn-borders (border
[vux-loader] 疑似不合法命名，将被忽略：.list-radius-show (shadow
[vux-loader] 疑似不合法命名，将被忽略：.fz (fz
[vux-loader] 疑似不合法命名，将被忽略：.pad12 (vlaue
[vux-loader] 疑似不合法命名，将被忽略：.w50_h50 (w
[vux-loader] 疑似不合法命名，将被忽略：.flex{display
[vux-loader] 疑似不合法命名，将被忽略：.flex-v{flex-direction
[vux-loader] 疑似不合法命名，将被忽略：.flex-1{flex
[vux-loader] 疑似不合法命名，将被忽略：.flex-align-center{align-items
[vux-loader] 疑似不合法命名，将被忽略：.flex-pack-center{justify-content
[vux-loader] 疑似不合法命名，将被忽略：.flex-pack-justify{justify-content
```

### What is Expected?
期待：
1. 运行起来就可以解析我全局的 less 文件了
2. 想想都开心
3. vux-loader 检测我得全部命名都不合法，在官方github中，发现了原来换成了 @vux-loader 。
4. 更换后，发现只有小部分命名不规范。
5. 我太菜了，就学会手册内的常用，不知道我得命名应该怎么改啊。怎么样的规范才合理了？及时我命名不合理，你警告下也可以啊，也不要忽略啊，这么玩，自己都玩死了。哈哈哈哈

### What is actually happening?
代码不能运行，我只想把项目vue2.x 转到 vue3.x。很辛苦啊，又是一天混过去了。

**Comment by LaoCheng-cjs** [comment]
懂了，原来是原因以下：

- @vux-loader 根本不支持less传参

```less
.list-radius-show (@shadow:0 5px 12px 4px rgba(0,0,0,0.06)){
    background: @c_f;
    /* box-shadow: @shadow;
    border-radius: 0.625rem; */
    padding: 0.625rem;
    margin-bottom: 0.9375rem;
}
```

- 当写的 less类与 { 写的非常挤也不行

```less
.flex-v{flex-direction:column;}
```


> 大家可以考虑下 style-resources-loader 。但是他和 @vux-loader 好像有些冲突。
