### ISSUE TITLE
vux.css中switch的样式缺失

### ISSUE THREAD

**Issue by terranc** [airyland/vux#377]
### Version
df00f042d53bcb1daec718d4c3bbb1a54a8d5e40

### Your Codes 

![image](https://cloud.githubusercontent.com/assets/224353/16828742/3f36331a-49c5-11e6-9319-7a0ac0142dca.png)

### Expected behavior and actual behavior.

查看样式发现，相比weui的demo，少了：
```css
.weui_cell_switch {
    padding-top: 6px;
    padding-bottom: 6px;
}
```
