### ISSUE TITLE
tab＋swiper组合使用，swiper－item中列表scroller滚动的问题

### ISSUE THREAD

**Issue by songhlc** [airyland/vux#479]
### iOS 

> For Android issues, please specify the brand, model and browser

### Your Codes 

``` html
<tab>
</tab>
<swiper>
    <swiper-item>
    <swiper-item>
    <swiper-item>
</swiper>
```

### Steps to reproduce the problem
1.使用tab＋swiper组件
2.期待效果，swiper下 swiper-item中展现的是一个列表，需要展现列表并支持滚动

遇到问题：
1.swiper如果不设置高度，则无发展示出item中的内容（目前是动态计算了可视区域高度来解决）
2.添加了样式
``` css
.vux-slider>.vux-swiper>.vux-swiper-item{
  overflow: auto;
}
```
在swiper-item中用的默认的滚动条，在ios里通过微信访问滚动不流畅，没有默认的阻尼效果，每次滚动区域也很少（不清楚是不是absolute里的滚动条不流畅导致的）
3.改成在swiper-item里嵌套里一个scroller ，无法向下滚动

请教我这样的场景是否当前不使用tab＋swiper组件来实现
