### ISSUE TITLE
Search组件CSS样式问题

### ISSUE THREAD

**Issue by JianleiZhang** [airyland/vux#493]
v0.1.3-rc9

``` html
<div class="weui_cells weui_cells_access vux-search_show" id="search_show" v-show="isFixed && results.length && value">
```

``` css
.weui_cells {
    background-color: #ffffff;
    font-size: 17px;
    line-height: 1.41176;
    margin-top: 1.17647em;
    overflow: hidden;
    position: relative;
}
```

这里的`margin-top: 1.17647em;`导致外边框多了20px。

但是官方例子里是正常的……

**Comment by JianleiZhang** [comment]
```css
.vux-search_show {
    height: 100%;
    margin-top: 0;
    overflow-y: auto;
}
```
应该是和这里的权重搞错了。
