### ISSUE TITLE
font-face 编译问题

### ISSUE THREAD

**Issue by majianxiong** [airyland/vux#564]
### 问题描述

在vux源码中添加了字体样式文件vux/src/styles/weui/icon/anticon.less，以及对应字体文件vux/src/styles/weui/fonts，并且在vux/src/components/loading/index.vue组件中引用了这个
字体，但是执行npm run xbuild命令，编译结果只能正常生成引用msiconfont.svg文件，其他msiconfont.eot，msiconfont.woff，msiconfont.ttf不能正常引用被找到，loading组件index.js
文件加载就会出错。
### Version

npm version v3.8.3
node v5.10.1
### Android or iOS

> N/A
### Your Codes

``` less
// font-face
// @icon-url： 字体源文件的地址
@font-face {
  font-family: 'anticon';
  src: url('../fonts/msiconfont.eot'); /* IE9*/
  src: url('../fonts/msiconfont.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('../fonts/msiconfont.woff') format('woff'), /* chrome、firefox */
  url('../fonts/msiconfont.ttf') format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/
  url('../fonts/msiconfont.svg') format('svg'); /* iOS 4.1- */
}
```

``` html
……
<style lang="less">
@import '../../styles/weui/widget/weui_tips/weui_mask';
@import '../../styles/weui/widget/weui_tips/weui_toast';
@import '../../styles/weui/icon/anticon';
</style>
……
```
### Expected behavior and actual behavior.

svg可以正常引用，但是其他msiconfont.eot，msiconfont.woff，msiconfont.ttf也能够正常被引用
### Steps to reproduce the problem
1. 添加字体样式 @font-face “anticon”
   ![image](https://cloud.githubusercontent.com/assets/887531/18379522/a133bec2-76a5-11e6-8dec-18a59fdd5acc.png)
2. 设置应用样式
   ![image](https://cloud.githubusercontent.com/assets/887531/18379637/27482b42-76a6-11e6-851d-c78a1779a8ee.png)
3. 构建
   ![image](https://cloud.githubusercontent.com/assets/887531/18379667/4f65a514-76a6-11e6-9018-ca6188b96196.png)
4. 生成目录 vux/dist/components-commonjs/loading
   ![image](https://cloud.githubusercontent.com/assets/887531/18379765/bd6d582c-76a6-11e6-94a5-b679b64b0592.png)
   可以正常应用msiconfont.svg文件
5. 错误
   ![default](https://cloud.githubusercontent.com/assets/887531/18380182/bb69980e-76a8-11e6-99c6-67e1a60106f3.png)
