### ISSUE TITLE
XHeader怎么设置固定

### ISSUE THREAD

**Issue by HopeFE** [airyland/vux#754]
VUX 0.13版本使用viewbox这个组件去设置，固定的头部。现在2版本用VUX怎么实现呢？这个需求还是蛮大的，我用以前的代码发现报错，希望作者能在XHeader里面给个DEMO啊？

**Comment by greedying** [comment]
不一样么。现在也有viewbox啊

**Comment by HopeFE** [comment]
是有但是我在移植过来的时候报错了

`[Vue warn]: Failed to resolve directive: ref 
(found in anonymous component - use the "name" option for better debugging messages.)`

`<view-box v-ref:view-box>
    <div slot="header" style="position:absolute;left:0;top:0;width:100%;z-index:100">
      <x-header>头部</x-header>
    </div>
</view-box>
`

**Comment by airyland** [comment]
@HopeFE Vue2没有`v-ref`，只有`ref=""`

**Comment by HopeFE** [comment]
我用fixed是可以的，但是滚动条会显示在header上 比较难看。2的DEMO里有这种固定的例子么？想参考下，不胜感激

**Comment by jackpt** [comment]
@HopeFE @airyland 我也遇到同样的问题，view-box + fixed之后，滚动条会出现在header之上。
期待更完美的解决方案

**Comment by HopeFE** [comment]
目前还不敢把VUX升到2，先把vuex给换掉@jackpt   。期待vux完善

**Comment by F-loat** [comment]
可以把内容区域设置为绝对定位，然后设置`overflow: auto;`就好了。
``` css
.content {
    position: absolute;
    top: 46px;
    bottom: 0;
    left: 0;
    right: 0;
    overflow: auto;
}
```
