### ISSUE TITLE
Form-Preview组件的样式问题

### ISSUE THREAD

**Issue by asingingfish** [airyland/vux#920]
### Android

> 模拟器及荣耀Android7.0均存在这个问题

### 问题描述

依据源码构建的Form-Preview组件会出现横向滚动条，debug后发现问题出在这里：

``` css
.weui-form-preview__hd:after {
  content: " ";
  position: absolute;
  left: 0;
  bottom: 0;
  width: 100%;
  height: 1px;
  border-bottom: 1px solid #D9D9D9;
  color: #D9D9D9;
  transform-origin: 0 100%;
  transform: scaleY(0.5);
  left: 15px;  /*在编译后的css中，多了个left样式*/
}
```

另外在文档中Form-Preview组件demo的代码部分将```:body-items```错写为```:bodyItems```。:)
