### ISSUE TITLE
less变量申请，申请icon颜色和尺寸

### ISSUE THREAD

**Issue by greedying** [airyland/vux#988]
weui-icon-success-color
weui-icon-success-font-size。

发现有些地方需要自定义合适的尺寸。

另外，icon组件还保留着一些老版的weui class。
比如
```script
    className () { // compatible with old type param
      return `weui-icon weui_icon_${this.type} weui-icon-${this.type.replace(/_/g, '-')}`
    }
```

以及一些应该是废弃的代码仍然保留
```css
.icon-big:before {
  font-size: 104px;
}

.icon-small:before {
  font-size: 12px;
}
````
